//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderID { get; set; }
        public int userID { get; set; }
        public System.DateTime orderDate { get; set; }
        public int orderStructure { get; set; }
        public decimal totalAmount { get; set; }
        public Nullable<decimal> discountAmount { get; set; }
        public string pickupPoint { get; set; }
    
        public virtual Medicines Medicines { get; set; }
        public virtual Users Users { get; set; }
    }
}
